# Generated by Django 4.1.7 on 2023-03-06 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0002_remove_party_author_id_member_party_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='user',
        ),
        migrations.AddField(
            model_name='party',
            name='member',
            field=models.ManyToManyField(to='party.member'),
        ),
        migrations.RemoveField(
            model_name='party',
            name='author',
        ),
        migrations.AddField(
            model_name='party',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
